import { useEffect, useRef, useState } from 'react'
import { ArrowRight, CalendarDays, Camera, ChevronRight, Copy, Heart, Link2, Plus, Share2, Smartphone, UsersRound, Zap } from 'lucide-react'
import type { CommonProps } from './appTypes'
import { Avatar, BrandMark, Field, Page, Signature, TopBack } from './UI'
import { blobToDataUrl, compressAvatar } from './lib/image'
import { isSupabaseConfigured, supabase } from './lib/supabase'
import { createRemoteCouple, joinRemoteCouple, saveRemoteProfile } from './lib/remoteStore'

export function Onboarding({ onStart,busy=false }: { onStart: () => void; busy?:boolean }) {
  return <div className="onboarding-screen">
    <div className="onboarding-art" aria-hidden><div className="big-heart heart-a"/><div className="big-heart heart-b"/><div className="orbit orbit-a"/><div className="orbit orbit-b"/><div className="tiny-note note-one">better together</div><div className="tiny-note note-two">every day ♡</div></div>
    <div className="onboarding-copy"><BrandMark/><h1>Hai cuộc sống khác nhau.<br/>Một nhịp chung.</h1><p>Together không ép hai người dính lấy nhau. Nó giúp cả hai nhìn thấy lịch làm việc, năng lượng và nhu cầu gần gũi — rồi tìm ra khoảng thời gian thật sự phù hợp.</p></div>
    <div className="feature-grid"><Feature icon={CalendarDays} title="Quản lý workdate" text="Biết lúc nào thật sự rảnh" tone="mint"/><Feature icon={Zap} title="Theo dõi năng lượng" text="Đỡ lên plan sai thời điểm" tone="peach"/><Feature icon={Heart} title="Hiểu nhu cầu gần gũi" text="Không ai phải đoán ý ai" tone="rose"/><Feature icon={UsersRound} title="Lên kế hoạch chung" text="Soft plan hoặc hard plan" tone="lilac"/></div>
    {isSupabaseConfigured&&<div className="privacy-note"><Smartphone size={19} aria-hidden="true"/><span><strong>Cài Together lên màn hình chính trước nhé.</strong> Trên iPhone: Chia sẻ → Thêm vào MH chính. Trên Android: menu trình duyệt → Cài đặt ứng dụng. Hãy mở bằng biểu tượng đó rồi bắt đầu để giữ tài khoản trên máy.</span></div>}
    <button className="primary-button onboarding-button" onClick={onStart} disabled={busy}>{busy?'Đang chuẩn bị…':'Bắt đầu'} <ArrowRight size={18}/></button><p className="small-note center">Bận rộn hơn, nhưng vẫn gần nhau hơn mỗi ngày.</p><Signature compact/>
  </div>
}
function Feature({ icon: Icon, title, text, tone }: { icon: typeof Heart; title: string; text: string; tone: string }) { return <div className={`feature-card ${tone}`}><span className="feature-icon"><Icon size={20}/></span><strong>{title}</strong><small>{text}</small></div> }

export function ProfileSetup({ state, updateState, onContinue, onBack, notify }: CommonProps & { onContinue: () => void; onBack:()=>void }) {
  const [name,setName]=useState(state.me.displayName==='Bạn'?'':state.me.displayName); const fileRef=useRef<HTMLInputElement>(null); const [busy,setBusy]=useState(false)
  const pickAvatar=async(file?:File)=>{ if(!file)return; setBusy(true); try{ const blob=await compressAvatar(file); let avatarUrl=await blobToDataUrl(blob); let avatarPath:string|undefined
    if(supabase){ const {data:userData}=await supabase.auth.getUser(); const userId=userData.user?.id; if(!userId||userId!==state.me.id)throw new Error('Tài khoản đã thay đổi. Hãy tải lại hồ sơ.'); avatarPath=`${userId}/avatar-${Date.now()}.webp`; const {error}=await supabase.storage.from('avatars').upload(avatarPath,blob,{contentType:'image/webp',upsert:false}); if(error) throw error; const signed=await supabase.storage.from('avatars').createSignedUrl(avatarPath,3600); avatarUrl=signed.data?.signedUrl??avatarUrl }
    if(supabase) await saveRemoteProfile(name.trim()||state.me.displayName||'Bạn',avatarPath,state.me.id)
    updateState(d=>{d.me.avatarUrl=avatarUrl;d.me.avatarPath=avatarPath}); notify('Ảnh đại diện đã sẵn sàng.')
  }catch(err){notify(err instanceof Error?err.message:'Không thể xử lý ảnh.','normal')}finally{setBusy(false)}}
  const next=async()=>{ const nextName=name.trim()||'Bạn'; try{if(supabase)await saveRemoteProfile(nextName,state.me.avatarPath,state.me.id)}catch(error){notify(error instanceof Error?error.message:'Không thể lưu hồ sơ.','normal');return} updateState(d=>{d.me.displayName=nextName}); onContinue() }
  return <Page className="setup-page"><TopBack title="Hồ sơ của bạn" onBack={onBack}/><div className="profile-hero"><div className="avatar-picker" onClick={()=>fileRef.current?.click()}><Avatar profile={state.me} size="xl"/><span className="camera-chip"><Camera size={17}/></span></div><input ref={fileRef} hidden type="file" accept="image/*" onChange={e=>pickAvatar(e.target.files?.[0])}/><button className="secondary-button slim" onClick={()=>fileRef.current?.click()}>{busy?'Đang xử lý…':'Tải ảnh lên'}</button><p>Ảnh chỉ dùng trong couple của bạn. Bản production dùng private Storage.</p></div><div className="form-stack"><Field label="Tên hiển thị"><input value={name} maxLength={60} onChange={e=>setName(e.target.value)} placeholder="Tên người ấy gọi bạn"/></Field><div className="privacy-note"><Heart size={16}/> Dữ liệu nhạy cảm không dùng để tạo “relationship score”. Together chỉ dùng nó để chọn thời điểm phù hợp.</div></div><button className="primary-button sticky-action" onClick={next} disabled={busy}>Tiếp tục</button><Signature compact/></Page>
}

export function Connect({ state, updateState, onDone, onBack, notify }: CommonProps & { onDone: () => void; onBack:()=>void }) {
  const initialInvite=()=>new URLSearchParams(window.location.search).get('invite')?.trim().toUpperCase()??''
  const [mode,setMode]=useState<'choose'|'invite'|'join'>(()=>initialInvite()?'join':'choose'); const [code,setCode]=useState(initialInvite); const [busy,setBusy]=useState(false); const [deepLinkMode,setDeepLinkMode]=useState(()=>Boolean(initialInvite())); const [joinError,setJoinError]=useState<string|null>(null); const autoJoinRef=useRef(false)
  const createBusyRef=useRef(false); const joinBusyRef=useRef(false); const mountedRef=useRef(true)
  useEffect(()=>()=>{mountedRef.current=false},[])
  const validInvite=(value:string)=>/^[A-F0-9]{10,32}$/.test(value.trim().toUpperCase())
  const create=async()=>{if(createBusyRef.current)return;createBusyRef.current=true;setBusy(true);try{if(supabase){const created=await createRemoteCouple(state.me.id);if(!mountedRef.current)return;updateState(d=>{d.id=created.id;d.inviteCode=created.code;d.inviteExpiresAt=created.expiresAt})}else updateState(d=>{d.inviteCode=`TOG${Math.random().toString(36).slice(2,8).toUpperCase()}`});if(!mountedRef.current)return;setMode('invite');notify('Đã tạo không gian chung. Gửi link này cho người yêu.') }catch(e){if(mountedRef.current)notify(e instanceof Error?e.message:'Không thể tạo couple.','normal')}finally{createBusyRef.current=false;if(mountedRef.current)setBusy(false)}}
  const join=async(inviteCode=code)=>{const normalized=inviteCode.trim().toUpperCase();if(!validInvite(normalized)){setJoinError('Mã mời chưa hợp lệ.');return notify('Nhập mã mời hợp lệ.','normal')}if(joinBusyRef.current)return;joinBusyRef.current=true;setBusy(true);setJoinError(null);try{if(supabase)await joinRemoteCouple(normalized,state.me.id);if(!mountedRef.current)return;const url=new URL(window.location.href);url.searchParams.delete('invite');window.history.replaceState(null,'',url);notify('Hai bạn đã kết nối.');onDone()}catch(e){if(!mountedRef.current)return;const message=e instanceof Error?e.message:'Không thể kết nối lời mời.';setJoinError(message);notify(message,'normal')}finally{joinBusyRef.current=false;if(mountedRef.current)setBusy(false)}}
  useEffect(()=>{if(!supabase||!deepLinkMode||autoJoinRef.current||code.trim().length<10)return;autoJoinRef.current=true;void join(code)},[])
  const inviteUrl=()=>`${window.location.origin}${import.meta.env.BASE_URL}?invite=${encodeURIComponent(state.inviteCode)}`
  const copy=async()=>{try{await navigator.clipboard.writeText(inviteUrl());notify('Đã sao chép link mời.')}catch{notify('Không sao chép được. Bạn có thể gửi mã bên trên.','normal')}}
  const share=async()=>{if(navigator.share){try{await navigator.share({title:'Together',text:'Cùng mình giữ nhịp mỗi ngày nhé',url:inviteUrl()})}catch{/* The share sheet can be dismissed intentionally. */}}else await copy()}
  const back=()=>{if(mode==='choose')onBack();else{setDeepLinkMode(false);setJoinError(null);setMode('choose')}}
  return <Page className="connect-page"><TopBack title="Kết nối cùng nhau" onBack={back}/><div className="center-heading"><span className="eyebrow">Bắt đầu một nhịp chung</span><h2>Hai người, một không gian riêng.</h2><p>Không có feed. Không public. Chỉ hai người.</p></div>{mode==='choose'?<div className="choice-stack"><button className="choice-card rose" onClick={create} disabled={busy}><span className="round-icon"><Plus/></span><div><strong>{busy?'Đang tạo…':'Tạo couple mới'}</strong><small>Nhận một link dùng một lần dành riêng cho người yêu</small></div><ChevronRight/></button><button className="choice-card mint" onClick={()=>{setDeepLinkMode(false);setJoinError(null);setMode('join')}}><span className="round-icon"><Link2/></span><div><strong>Tham gia bằng link hoặc mã</strong><small>Dán mã người yêu gửi cho bạn</small></div><ChevronRight/></button></div>:mode==='invite'?<div className="invite-card"><Heart size={28}/><span className="eyebrow">Mã mời riêng của hai bạn</span><strong className="invite-code">{state.inviteCode}</strong><p>Link có hiệu lực 7 ngày và chỉ dùng một lần. Người ấy chỉ cần mở link trên điện thoại riêng; Together sẽ tự kết nối sau bước đặt tên.</p><button className="primary-button" onClick={share}><Share2 size={16}/> Chia sẻ link mời</button><button className="secondary-button" onClick={copy}><Copy size={16}/> Sao chép link</button><button className="text-button" onClick={onDone}>Vào Together</button></div>:deepLinkMode?<div className="invite-card" aria-live="polite"><Link2 size={28}/><span className="eyebrow">Lời mời của hai bạn</span><strong>{busy?'Đang kết nối…':joinError?'Chưa kết nối được':'Đang chuẩn bị kết nối…'}</strong><p>{joinError??'Together đang xác nhận lời mời trên thiết bị này. Bạn không cần nhập lại mã.'}</p>{joinError&&<button className="primary-button" onClick={()=>void join(code)} disabled={busy}>{busy?'Đang thử lại…':'Thử kết nối lại'}</button>}<button className="text-button" onClick={()=>{setDeepLinkMode(false);setJoinError(null);setCode('');setMode('join')}}>Nhập mã khác</button></div>:<div className="invite-card"><Link2 size={28}/><span className="eyebrow">Mã người yêu gửi cho bạn</span><label htmlFor="join-code" className="form-hint">Kết nối bằng mã mời</label><input id="join-code" value={code} maxLength={32} onChange={e=>{setJoinError(null);setCode(e.target.value.toUpperCase())}} placeholder="Nhập hoặc dán mã mời" autoCapitalize="characters" autoComplete="off"/><button className="primary-button" onClick={()=>void join()} disabled={busy||code.trim().length<10}>{busy?'Đang kết nối…':'Kết nối'}</button>{joinError&&<p className="form-hint" role="alert">{joinError}</p>}<button className="text-button" onClick={()=>setMode('choose')}>Quay lại</button>{!isSupabaseConfigured&&<button className="text-button" onClick={onDone}>Tiếp tục bản demo</button>}</div>}<div className="line-art">two different lives · one beautiful rhythm ♡</div><Signature compact/></Page>
}
