import { useState } from 'react'
import { BriefcaseBusiness, CalendarDays, Check, Clock3, Coffee, Heart, Laptop, MapPin, MoonStar, Zap } from 'lucide-react'
import type { CommonProps } from './appTypes'
import type { AvailabilityBlock, AvailabilityStatus, DailyState, PlanType, SharedPlan, WeeklyCheckin, WorkSchedule, WorkType } from './types'
import { Avatar, Field, Page, TopBack } from './UI'
import { addAvailability, addPlan, addWork, upsertCheckin, upsertDailyState } from './lib/demoStore'
import { saveRemoteAvailability, saveRemoteCheckin, saveRemoteDaily, saveRemotePlan, saveRemoteWork } from './lib/remoteStore'
import { supabase } from './lib/supabase'

const todayDate=()=>new Date().toISOString().slice(0,10)
const uid=(p:string)=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`
const formatDate=(iso:string)=>new Intl.DateTimeFormat('vi-VN',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date(`${iso}T12:00:00`))
const getWeekStart=()=>{const x=new Date(),day=x.getDay()||7;x.setDate(x.getDate()-day+1);return x.toISOString().slice(0,10)}
const energyLabels=['Rất mệt','Hơi đuối','Bình thường','Khá ổn','Rất tốt']; const closenessLabels=['Cần không gian','Ở riêng cũng ổn','Có gặp thì vui','Muốn gần nhau','Rất muốn ở bên nhau']
const workMeta:Record<WorkType,{label:string;icon:typeof Coffee}>={office:{label:'Văn phòng',icon:BriefcaseBusiness},remote:{label:'Remote',icon:Laptop},shift:{label:'Ca làm',icon:Clock3},off:{label:'Nghỉ',icon:Coffee},other:{label:'Khác',icon:CalendarDays}}
const availabilityMeta:Record<AvailabilityStatus,{label:string;className:string}>={available:{label:'Rảnh',className:'mint'},busy:{label:'Bận',className:'rose'},prefer_alone:{label:'Muốn ở một mình',className:'lilac'},want_together:{label:'Muốn gặp',className:'peach'}}

export function DailyStateForm({state,updateState,onClose,notify}:CommonProps&{onClose:()=>void}){const date=todayDate(),current=state.dailyStates.find(x=>x.userId===state.me.id&&x.date===date),[energy,setEnergy]=useState(current?.energy??3),[closeness,setCloseness]=useState(current?.closeness??3),[note,setNote]=useState(current?.note??'');const save=async()=>{const next:DailyState={userId:state.me.id,date,energy,closeness,note};try{if(supabase)await saveRemoteDaily(state.id,next)}catch(e){notify(e instanceof Error?e.message:'Không thể lưu trạng thái.','normal');return}updateState(d=>upsertDailyState(d,next));notify('Đã cập nhật trạng thái hôm nay.');onClose()};return <Page className="form-page"><TopBack title="Hôm nay bạn thế nào?" onBack={onClose}/><div className="form-intro"><span className="eyebrow">{formatDate(date)}</span><h2>Một tín hiệu nhỏ giúp người kia hiểu bạn hơn.</h2><p>Không có đáp án đúng. Trạng thái này chỉ dành cho hôm nay.</p></div><Scale label="Mức năng lượng" value={energy} onChange={setEnergy} tone="energy" labels={energyLabels}/><Scale label="Mức muốn gần nhau" value={closeness} onChange={setCloseness} tone="heart" labels={closenessLabels}/><Field label="Chia sẻ thêm (tuỳ chọn)"><textarea rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Hôm nay hơi mệt, chỉ muốn ở cạnh nhau nhẹ nhàng."/></Field><div className="privacy-note"><MoonStar size={16}/> Chỉ người trong couple mới nhìn thấy trạng thái này.</div><button className="primary-button sticky-action" onClick={save}>Lưu trạng thái</button></Page>}
function Scale({label,value,onChange,tone,labels}:{label:string;value:number;onChange:(v:number)=>void;tone:string;labels:string[]}){const Icon=tone==='heart'?Heart:Zap;return <section className="scale-section"><div className="scale-label"><Icon size={18}/><strong>{label}</strong></div><div className={`scale-buttons ${tone}`}>{[1,2,3,4,5].map(n=><button key={n} className={n===value?'active':''} onClick={()=>onChange(n)}><Icon size={22} fill={n<=value?'currentColor':'none'}/></button>)}</div><strong className="scale-current">{labels[value-1]}</strong></section>}

export function WorkForm({state,updateState,onClose,notify}:CommonProps&{onClose:()=>void}){const[type,setType]=useState<WorkType>('office'),[date,setDate]=useState(todayDate()),[start,setStart]=useState('09:00'),[end,setEnd]=useState('17:30'),[note,setNote]=useState(''),[repeat,setRepeat]=useState(false);const save=async()=>{const next:WorkSchedule={id:uid('work'),userId:state.me.id,date,start,end,type,note,repeatsWeekly:repeat};try{if(supabase)await saveRemoteWork(state.id,next)}catch(e){notify(e instanceof Error?e.message:'Không thể lưu workdate.','normal');return}updateState(d=>addWork(d,next));notify('Đã thêm workdate.');onClose()};return <Page className="form-page"><TopBack title="Thêm lịch làm việc" onBack={onClose}/><div className="form-stack"><div><label className="field-label">Loại công việc</label><div className="option-grid work-options">{(Object.keys(workMeta) as WorkType[]).map(key=>{const Icon=workMeta[key].icon;return <button key={key} className={type===key?'active':''} onClick={()=>setType(key)}><Icon size={19}/><span>{workMeta[key].label}</span></button>})}</div></div><Field label="Ngày"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field><div className="two-cols"><Field label="Từ"><input type="time" value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="Đến"><input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></Field></div><Field label="Ghi chú (tuỳ chọn)"><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Họp team buổi sáng…"/></Field><label className="toggle-row"><button className={`toggle ${repeat?'on':''}`} onClick={()=>setRepeat(!repeat)}><span/></button><div><strong>Đánh dấu là lịch lặp lại</strong><small>Lặp lại hàng tuần</small></div></label></div><button className="primary-button sticky-action" onClick={save}>Lưu lịch làm việc</button></Page>}

export function AvailabilityForm({state,updateState,onClose,notify}:CommonProps&{onClose:()=>void}){const[status,setStatus]=useState<AvailabilityStatus>('available'),[date,setDate]=useState(todayDate()),[start,setStart]=useState('19:00'),[end,setEnd]=useState('22:00'),[note,setNote]=useState('');const save=async()=>{const next:AvailabilityBlock={id:uid('availability'),userId:state.me.id,date,start,end,status,note};try{if(supabase)await saveRemoteAvailability(state.id,next)}catch(e){notify(e instanceof Error?e.message:'Không thể lưu lịch rảnh.','normal');return}updateState(d=>addAvailability(d,next));notify('Đã cập nhật lịch rảnh.');onClose()};return <Page className="form-page"><TopBack title="Thêm lịch của bạn" onBack={onClose}/><div className="form-stack"><div><label className="field-label">Bạn muốn đánh dấu khoảng này là</label><div className="option-grid availability-options">{(Object.keys(availabilityMeta) as AvailabilityStatus[]).map(key=><button key={key} className={`${availabilityMeta[key].className} ${status===key?'active':''}`} onClick={()=>setStatus(key)}>{availabilityMeta[key].label}</button>)}</div></div><Field label="Ngày"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field><div className="two-cols"><Field label="Từ"><input type="time" value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="Đến"><input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></Field></div><Field label="Ghi chú (tuỳ chọn)"><textarea rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Ví dụ: Có thể đi ăn tối."/></Field></div><button className="primary-button sticky-action" onClick={save}>Lưu</button></Page>}

export function PlanForm({state,updateState,onClose,notify}:CommonProps&{onClose:()=>void}){const[type,setType]=useState<PlanType>('soft'),[title,setTitle]=useState(''),[date,setDate]=useState(todayDate()),[start,setStart]=useState('19:00'),[end,setEnd]=useState('21:00'),[location,setLocation]=useState(''),[note,setNote]=useState('');const save=async()=>{if(!title.trim())return notify('Thêm một cái tên cho kế hoạch nhé.','normal');const next:SharedPlan={id:uid('plan'),title:title.trim(),date,start,end,type,status:type==='hard'?'confirmed':'proposed',location,note,createdBy:state.me.id};try{if(supabase)await saveRemotePlan(state.id,next)}catch(e){notify(e instanceof Error?e.message:'Không thể tạo kế hoạch.','normal');return}updateState(d=>addPlan(d,next));notify('Đã tạo kế hoạch chung.');onClose()};return <Page className="form-page"><TopBack title="Tạo kế hoạch chung" onBack={onClose}/><div className="plan-type-tabs"><button className={type==='soft'?'active':''} onClick={()=>setType('soft')}><strong>Kế hoạch mềm</strong><small>Có thể thay đổi</small></button><button className={type==='hard'?'active':''} onClick={()=>setType('hard')}><strong>Kế hoạch chắc chắn</strong><small>Đã xác nhận</small></button></div><div className="form-stack"><Field label="Tiêu đề"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Đi xem phim 🎬"/></Field><Field label="Ngày"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field><div className="two-cols"><Field label="Từ"><input type="time" value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="Đến"><input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></Field></div><Field label="Địa điểm (tuỳ chọn)"><input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Quán quen, ở nhà…"/></Field><Field label="Ghi chú (tuỳ chọn)"><textarea rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Nhớ chọn phim trước nha 💕"/></Field></div><div className="members-preview"><span className="eyebrow">Thành viên</span><div><Avatar profile={state.me} size="sm"/><Avatar profile={state.partner} size="sm"/><strong>{state.me.displayName} + {state.partner.displayName}</strong></div></div><button className="primary-button sticky-action" onClick={save}>Tạo kế hoạch</button></Page>}

export function PlanDetail({plan,state,onClose}:CommonProps&{plan:SharedPlan;onClose:()=>void}){return <Page className="detail-page"><TopBack title="Chi tiết kế hoạch" onBack={onClose}/><div className="plan-detail-hero"><div className="cinema-illustration"><span/><span/><span/><i/></div><div className="detail-title"><div><span className={`status-chip ${plan.type}`}>{plan.type==='hard'?'Chắc chắn':'Kế hoạch mềm'}</span><h1>{plan.title}</h1></div><Heart size={26}/></div></div><div className="detail-list"><div><CalendarDays/><span>{formatDate(plan.date)}</span></div><div><Clock3/><span>{plan.start} – {plan.end}</span></div>{plan.location&&<div><MapPin/><span>{plan.location}</span></div>}</div>{plan.note&&<blockquote>“{plan.note}”</blockquote>}<section className="detail-members"><span className="eyebrow">Thành viên</span><Member profile={state.me}/><Member profile={state.partner}/></section><div className="detail-actions"><button className="secondary-button">Chỉnh sửa</button><button className="secondary-button danger-outline">Huỷ kế hoạch</button></div></Page>}
function Member({profile}:{profile:{displayName:string;avatarUrl?:string;id:string;avatarPath?:string}}){return <div className="member-row"><Avatar profile={profile} size="md"/><div><strong>{profile.displayName}</strong><small>Đã tham gia</small></div><Check size={17}/></div>}

export function CheckinForm({state,updateState,onClose,notify}:CommonProps&{onClose:()=>void}){const weekStart=getWeekStart(),current=state.checkins.find(x=>x.userId===state.me.id&&x.weekStart===weekStart),[feeling,setFeeling]=useState<1|2|3>(current?.feeling??2),[note,setNote]=useState(current?.note??'');const save=async()=>{const next:WeeklyCheckin={userId:state.me.id,weekStart,feeling,note};try{if(supabase)await saveRemoteCheckin(state.id,next)}catch(e){notify(e instanceof Error?e.message:'Không thể gửi check-in.','normal');return}updateState(d=>upsertCheckin(d,next));notify('Đã gửi check-in tuần này.');onClose()};return <Page className="form-page checkin-page"><TopBack title="Weekly check-in" onBack={onClose}/><div className="form-intro"><span className="eyebrow">Tuần này của bạn thế nào?</span><h2>Thời gian bên nhau so với điều bạn cần?</h2><p>Không chấm điểm. Chỉ là tín hiệu để tuần sau dễ điều chỉnh hơn.</p></div><div className="feeling-options"><button className={feeling===1?'active':''} onClick={()=>setFeeling(1)}><span>☹</span><strong>Quá ít</strong></button><button className={feeling===2?'active':''} onClick={()=>setFeeling(2)}><span>☺</span><strong>Vừa đủ</strong></button><button className={feeling===3?'active':''} onClick={()=>setFeeling(3)}><span>◔</span><strong>Quá nhiều</strong></button></div><Field label="Chia sẻ thêm (tuỳ chọn)"><textarea rows={4} value={note} onChange={e=>setNote(e.target.value)} placeholder="Tuần này ổn áp! 💕"/></Field><div className="privacy-note"><Heart size={16}/> Câu trả lời được giữ riêng cho tới khi cả hai cùng hoàn thành.</div><button className="primary-button sticky-action" onClick={save}>Gửi phản hồi</button></Page>}
